# Generated by Django 4.2 on 2024-01-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietime',
            name='show_time',
            field=models.TimeField(),
        ),
    ]
