# Generated by Django 4.2.9 on 2024-02-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
