# Generated by Django 4.2.7 on 2024-02-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_remove_movieticket_seat_movieticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticket',
            name='razorpay_order_id',
            field=models.CharField(default='Not Paid', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='razorpay_payment_id',
            field=models.CharField(default='Not Paid', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='razorpay_signature',
            field=models.CharField(default='Not Paid', max_length=255, null=True),
        ),
    ]
