# Generated by Django 4.2.7 on 2024-02-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_movieticket_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticket',
            name='movie_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.movielanguage'),
        ),
    ]
